### ISSUE TITLE
Wrong assignment

### ISSUE THREAD

**Issue by gianluca1606** [RoboJackets/hungarian#1]
Hello, first of all thanks for the implementation.

I have the following matrix at the beginning:

![image](https://user-images.githubusercontent.com/61363342/98481753-d8efc700-21fc-11eb-932a-810c49d1c0c3.png)

The cost matrix is corret as you can see here: 

http://www.hungarianalgorithm.com/solve.php?c=4-4-3-4-4-4-4-4-3-4--1-1-4-5-5-3-3-2-4-5--5-3-5-1-1-2-5-5-5-6--6-5-1-2-6-1-6-3-6-1--7-6-6-6-7-5-7-6-7-7--3-7-7-7-8-6-2-7-8-3--8-2-2-8-2-7-1-8-9-8--9-8-8-9-9-8-8-9-2-9--10-9-9-3-3-9-9-10-1-2--2-10-10-10-10-10-10-1-10-10&random=1

This is the result of your implementation:

`cost-matrix:
 [    0     0     0     0     0     1     1     0     1     1 ]
 [    0     0     4     4     4     3     3     1     5     5 ]
 [    4     2     5     0     0     2     5     4     6     6 ]
 [    4     3     0     0     4     0     5     1     6     0 ]
 [    1     0     1     0     1     0     2     0     3     2 ]
 [    0     4     5     4     5     4     0     4     7     1 ]
 [    6     0     1     6     0     6     0     6     9     7 ]
 [    5     4     5     5     5     5     5     5     0     6 ]
 [    7     6     7     0     0     7     7     7     0     0 ]
 [    1     9    10     9     9    10    10     0    11    10 ]`

But the assignment is not corret:

`assignment:
 [    0     0     1     0     0     0     0     0     0     0 ]
 [    1     0     0     0     0     0     0     0     0     0 ]
 [    0     0     0     1     0     0     0     0     0     0 ]
 [    0     0     0     0     0     0     0     0     0     1 ]
 [    0     0     0     0     0     1     0     0     0     0 ]
 [    0     0     0     0     0     0     1     0     0     0 ]
 [    0     1     0     0     0     0     0     0     0     0 ]
 [    0     0     0     0     0     0     0     0     1     0 ]
 [    0     0     0     0     1     0     0     0     0     0 ]
 [    0     0     0     0     0     0     0     1     0     0 ]`

You can check it on the link above.

If you could fix it, this would be very kind 👍

**Comment by kberzinch** [comment]
Hi there, unfortunately this repository is no longer maintained. I will be marking it as archived right after I close this issue. If you are interested in changing this behavior, feel free to fork the repository.
